### ISSUE TITLE
download_hemicycle.pl fails or misses files (not confirmed)

### ISSUE THREAD

**Issue by paulineleon** [regardscitoyens/nosdeputes.fr#131]
I did not investigate and it may not be an issue with the script itself. But I figured better to just write this down for when (if)  it happens again. 

* Two files were not downloaded although they exist http:__www.assemblee-nationale.fr_15_cri_2019-2020_20200051.asp http:__www.assemblee-nationale.fr_15_cri_2018-2019_20190274.asp (maybe they are not in the page)
* One file http:__www.assemblee-nationale.fr_15_cri_2019-2020_20200129.asp was downloaded but contained binary instead of the expected HTML (maybe the server misbehaved)

**Comment by RouxRC** [comment]
That's weird, maybe there should be more tests within the script to ensure the content is actual html and retry the download a couple times otherwise
For the first issue I'm not sure I get the problem: you got the files but they were empty? The code does a test to check whether files have a size so I would expect such behavior not to happen, but maybe the files did weight a little something?

**Comment by paulineleon** [comment]
> For the first issue I'm not sure I get the problem: you got the files but they were empty? 

The files were missing. Maybe they are also missing from the page, I did not check. If you don't mind I propose we leave this open for a month or two and close it if nobody ran into this again by then. What do you think?

**Comment by RouxRC** [comment]
As you like, although I don't think many other people will use by then ;)

**Comment by paulineleon** [comment]
> I don't think many other people will use by then ;)

No human indeed! But a [gentle bot](https://git.en-root.org/tricoteuses/html/comptes-rendus/-/blob/master/update.sh#L25)  will add to [a repository daily](https://git.en-root.org/tricoteuses/html/comptes-rendus/-/commits/master). And [another bot](https://git.en-root.org/tricoteuses/tricoteuses-assemblee-qa/-/blob/master/.gitlab-ci.yml#L51) runs consistency checks like [this one](https://git.en-root.org/tricoteuses/tricoteuses-assemblee/-/blob/master/src/bugs/agenda-00002.ts) and will notice if something is missing or corrupt.

**Comment by RouxRC** [comment]
sounds good then!

**Comment by RouxRC** [comment]
Ha, and since you version the compte-rendus, you might want to use the script differently: AN regularily updates these CR, so versioning it could be interesting (for instance you could delete the 50 last ones before running the script everytime). We don't have the manpower to handle these updates and we rather wait a few hours/days before loading them and only reload if something critical is pointed to us here.

**Comment by paulineleon** [comment]
Thanks for the hint :100: . An issue [was created](https://git.en-root.org/tricoteuses/html/comptes-rendus/issues/1) to not forget about it.

**Comment by RouxRC** [comment]
obsolete since AN's redesign
