### ISSUE TITLE
QoL - yield json député list as an object or a map with "nom" as key instead of an array

### ISSUE THREAD

**Issue by Guillaume-Levrier** [regardscitoyens/nosdeputes.fr#180]
https://www.nosdeputes.fr/deputes/json yields an array of objects such as 

```js
[{depute:
    {"nom_de_famille":"Du Lac",
     "prenom": "Perceval"
    }
}]
```

While it would be much easier to get:

```js
{"Du Lac":
    {
    "prenom":"Perceval"
    }
}
```

**Comment by boogheta** [comment]
Like I told you, the format of the API being used already in production services, we won't change its structure, the most we can do is add new fields.
Regardless, I disagree that a map would be more practical, for most users having an array is simplier to manipulate than a dictionary based on strings which could be spelled differently from other sources.
IMHO the main problem with the current architecture is those "depute" keys, normally we should only have [{"id": , "nom":}, ...] but this is a legacy situation due to the fact the json is built based on exactly the same structure as the xml, which requires such headings.

**Comment by Guillaume-Levrier** [comment]
I do understand that you can't change this format, but maybe creating a new route could be a possibility? 

I agree with the array option, creating a map from it would be easy enough.

**Comment by boogheta** [comment]
It could, but this is really not a priority since you can easily transform from one to the other in your reuse in a a couple lines of code

**Comment by Guillaume-Levrier** [comment]
Indeed, that's a quality of life issue, not a breaking one. Thank you for your answers!
