### ISSUE TITLE
QoL - ID type assertion consistency in JSON data

### ISSUE THREAD

**Issue by Guillaume-Levrier** [regardscitoyens/nosdeputes.fr#181]
In https://www.nosdeputes.fr/deputes/json, id is asserted as an **Int**, while in JSON amendment API data (ie http://www.nosdeputes.fr/api/document/Amendement/105967/json) id is asserted as a **String**, which makes equivalence testing fail because of type mismatch. 

Would be nice to have both either in Int or String.

**Comment by boogheta** [comment]
LOL
It was an integer before in the latter but I changed it to strings because of your report there was an actual problem with documents id not being integers but strings.
Will try and make it a specific rule only for Documents

**Comment by Guillaume-Levrier** [comment]
Well in that case maybe making all id strings would make sense?

**Comment by boogheta** [comment]
Well actually I misundestood your problem, you're talking about parlementaire_ids not the amendment itself and the fix I did was corresponding to other routes. In fact the problem here since to come from the toArray function of sfDoctrineRecords which would need to be overwritten.
Although I believe this is really not a critical issue since you can cast or make your tests be type-insensitive (JS has an explicit way to distinguish between the two kind of tests)
And no we won't change all ids to string which would require database structure change which we canot allow.
